name: Coverage

on:
  push:
    branches: [ main, feature/**, task/**, fix/** ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: npm -v
    - run: node -v
    - run: npm ci
    - run: npm run coverage:check
