name: Coverage

on:
  push:
    branches: [ main, feature/**, task/** ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn set version berry
    - run: yarn install
    - run: yarn coverage:check
