name: Check coverage

on:
  push:
    branches: [ feature/** ]

jobs:
  coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [ifca, scramjet]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: cd packages/${{ matrix.package }} && npm ci && npm run check:coverage
