---
name: Release framework-js

on:
  push:
    tags:
      - "v*"

env:
  registry: https://registry.npmjs.org/

jobs:
  run:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get tag branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }} |grep "main" )
          branch=${raw##*/}
          echo "BRANCH=$branch" >> $GITHUB_ENV
          echo ${{ env.BRANCH }}

      - name: Exit if tag not on main branch
        run: if [[ "${{ env.BRANCH }}" != 'main' ]];then exit 1; fi

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ env.registry }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Instal deps
        run: npm i

      - name: Build dist package
        run: npm run dist

      - name: Publish dist package as public one
        run: npm publish dist/ --access restricted
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Check npm package
        run: npm run test:release -- ${{ steps.get_version.outputs.VERSION }}
