name: Tests

on:
  push:
    branches: [ main, feature/** ]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        package: [ifca, scramjet]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd packages/${{ matrix.package }} && npm ci && npm run test
