name: Tests

on:
  push:
    branches: [ main, feature/**, task/** ]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn set version berry
    - run: yarn -v
    - run: yarn install
    - run: yarn test
