name: Tests

on:
  push:
    branches: [ main, feature/**, task/** ]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: npm -v
    - run: node -v
    - run: npm ci
    - run: npm test
